### ISSUE TITLE
outil diag i2m2

### ISSUE THREAD

**Issue by YvesHeno** [AnthonyDEBUR/tools4DCE#13]
Bonjour Anthony, je n'arrive pas à faire fonctionner ton script calcule_SEEE_ODinvertebres. La donnée d'entree est la même que pour le script qui calcule les métriques de l'I2M2. Cela semble être lié au webservice?

**Comment by AnthonyDEBUR** [comment]
Salut Yves-Marie,

Je viens de tester via l'exemple de la vignette : https://rpubs.com/ADebur/ODInvertebres et tout fonctionne. Peut-être effectivement y'a t'il eu une indisponibilité de l'API (elle sera indisponible ce jeudi, c'est écrit sur l site du SEEE). N'hésite pas à revenir vers moi si ça ne fonctionne toujours pas.

Bonne journée

**Comment by YvesHeno** [comment]
Ok merci, je retente

YM
